/**
 * case0003_captions.ts — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case 3
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the 1.5s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {start: number; end: number; who: string; text: string};

export const CAPTIONS: Cue[] = [
  {start: 0.0, end: 2.275, who: 'RAY', text: 'There\'s a company that decides if you\'re allowed to rent.'},
  {start: 2.54, end: 5.671, who: 'DEE', text: 'The government sued a company called RentGrow in July.'},
  {start: 5.93, end: 6.933, who: 'RAY', text: 'For what?'},
  {start: 7.19, end: 10.22, who: 'DEE', text: 'Their reports said people were evicted more times than they were.'},
  {start: 10.48, end: 11.717, who: 'RAY', text: 'How do you get that wrong?'},
  {start: 11.98, end: 14.378, who: 'DEE', text: 'They counted the same eviction twice.'},
  {start: 14.63, end: 15.915, who: 'RAY', text: 'The same eviction.'},
  {start: 16.18, end: 19.559, who: 'DEE', text: 'It\'s one case listed twice on the same report.'},
  {start: 19.82, end: 22.851, who: 'RAY', text: 'So you call and say, it\'s one eviction.'},
  {start: 23.11, end: 25.03, who: 'DEE', text: 'They marked the dispute invalid.'},
  {start: 25.29, end: 25.893, who: 'RAY', text: 'So?'},
  {start: 26.15, end: 29.834, who: 'DEE', text: 'When people asked what was in their file, they left out where it came from.'},
  {start: 30.1, end: 32.131, who: 'RAY', text: 'So you can\'t even find the thing to argue with.'},
  {start: 32.39, end: 35.285, who: 'DEE', text: 'They told the landlord something different than they told you.'},
  {start: 35.54, end: 38.235, who: 'RAY', text: 'I\'m not the customer.'},
  {start: 38.5, end: 39.243, who: 'DEE', text: 'No.'},
  {start: 39.5, end: 43.05, who: 'INSTITUTION', text: 'Reasonable procedures to assure maximum possible accuracy.'},
  {start: 43.31, end: 46.013, who: 'RAY', text: 'They paid two and a quarter million dollars.'},
  {start: 46.27, end: 49.309, who: 'RAY', text: 'The landlord is still their customer tomorrow.'},
];

/** Seconds of finished episode: last spoken word plus the 1.5s tail. */
export const TOTAL = 50.81;

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
};
