/**
 * case0002_captions.ts — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case 2
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the 1.5s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {start: number; end: number; who: string; text: string};

export const CAPTIONS: Cue[] = [
  {start: 0.0, end: 4.388, who: 'RAY', text: 'Ford recalled its hybrid SUVs over a noise they\'re required to make.'},
  {start: 4.65, end: 7.677, who: 'DEE', text: 'It doesn\'t always play. That\'s the recall.'},
  {start: 7.94, end: 9.611, who: 'RAY', text: 'So fix it.'},
  {start: 9.87, end: 15.152, who: 'DEE', text: 'They did. Software update in October, letters mailed November fifth.'},
  {start: 15.41, end: 18.905, who: 'DEE', text: 'Forty-three thousand, four hundred thirty-eight.'},
  {start: 19.16, end: 25.303, who: 'DEE', text: 'It\'s back. Sixty-six thousand, three hundred eighty-three.'},
  {start: 25.57, end: 31.417, who: 'DEE', text: 'NHTSA calls it an expansion. The ones they fixed have to be fixed again.'},
  {start: 31.67, end: 36.263, who: 'DEE', text: 'The only fix they have is for the version with twenty-eight speakers.'},
  {start: 36.53, end: 40.993, who: 'RAY', text: 'Twenty-eight speakers. That\'s how they decide who gets fixed.'},
  {start: 41.25, end: 46.895, who: 'INSTITUTION', text: 'Interim letters notifying owners of the safety risk are expected to be mailed August third.'},
  {start: 47.15, end: 48.14, who: 'RAY', text: 'That\'s tomorrow.'},
  {start: 48.41, end: 50.643, who: 'RAY', text: 'I still have the first letter.'},
];

/** Seconds of finished episode: last spoken word plus the 1.5s tail. */
export const TOTAL = 52.14;

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
};
