/**
 * case0003_faces.ts — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case 3
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {t: number; emotion: string};

export const FACES: Record<string, FaceBeat[]> = {
  DEE: [{t: 0, emotion: 'squint'}, {t: 2.54, emotion: 'flat'}, {t: 5.93, emotion: 'squint'}, {t: 7.19, emotion: 'flat'}, {t: 10.48, emotion: 'smug'}, {t: 11.98, emotion: 'flat'}, {t: 16.18, emotion: 'smug'}, {t: 19.82, emotion: 'flat'}, {t: 25.29, emotion: 'smug'}, {t: 26.15, emotion: 'flat'}, {t: 30.1, emotion: 'smug'}, {t: 32.39, emotion: 'flat'}, {t: 35.54, emotion: 'squint'}, {t: 38.5, emotion: 'smug'}, {t: 39.5, emotion: 'flat'}, {t: 43.31, emotion: 'smug'}, {t: 46.27, emotion: 'squint'}],
  RAY: [{t: 0, emotion: 'flat'}, {t: 2.54, emotion: 'squint'}, {t: 5.93, emotion: 'angry'}, {t: 7.19, emotion: 'squint'}, {t: 10.48, emotion: 'angry'}, {t: 11.98, emotion: 'shock'}, {t: 14.63, emotion: 'squint'}, {t: 16.18, emotion: 'shock'}, {t: 19.82, emotion: 'angry'}, {t: 23.11, emotion: 'shock'}, {t: 25.29, emotion: 'squint'}, {t: 30.1, emotion: 'angry'}, {t: 32.39, emotion: 'shock'}, {t: 35.54, emotion: 'flat'}, {t: 39.5, emotion: 'angry'}, {t: 43.31, emotion: 'flat'}, {t: 46.27, emotion: 'angry'}],
};

/** The expression in force for `who` at a global frame. */
export const emotionAt = (who: string, f: number): string => {
  const beats = FACES[who];
  if (!beats || !beats.length) return 'neutral';
  const t = f / 30;
  let cur = beats[0].emotion;
  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }
  return cur;
};
