/**
 * case0002_faces.ts — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case 2
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {t: number; emotion: string};

export const FACES: Record<string, FaceBeat[]> = {
  DEE: [{t: 0, emotion: 'flat'}, {t: 7.94, emotion: 'squint'}, {t: 9.87, emotion: 'neutral'}, {t: 15.41, emotion: 'flat'}, {t: 19.16, emotion: 'smug'}, {t: 25.57, emotion: 'flat'}, {t: 31.67, emotion: 'squint'}, {t: 36.53, emotion: 'flat'}, {t: 41.25, emotion: 'worried'}, {t: 47.15, emotion: 'squint'}, {t: 48.41, emotion: 'flat'}],
  RAY: [{t: 0, emotion: 'flat'}, {t: 4.65, emotion: 'squint'}, {t: 7.94, emotion: 'angry'}, {t: 9.87, emotion: 'flat'}, {t: 15.41, emotion: 'squint'}, {t: 19.16, emotion: 'shock'}, {t: 25.57, emotion: 'angry'}, {t: 31.67, emotion: 'shock'}, {t: 36.53, emotion: 'smug'}, {t: 41.25, emotion: 'squint'}, {t: 47.15, emotion: 'flat'}, {t: 48.41, emotion: 'angry'}],
};

/** The expression in force for `who` at a global frame. */
export const emotionAt = (who: string, f: number): string => {
  const beats = FACES[who];
  if (!beats || !beats.length) return 'neutral';
  const t = f / 30;
  let cur = beats[0].emotion;
  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }
  return cur;
};
