/**
 * case0004_faces.ts — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case 4
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {t: number; emotion: string};

export const FACES: Record<string, FaceBeat[]> = {
  DEE: [{t: 0, emotion: 'flat'}, {t: 1.98, emotion: 'squint'}, {t: 3.91, emotion: 'flat'}, {t: 8.56, emotion: 'squint'}, {t: 10.25, emotion: 'flat'}, {t: 15.46, emotion: 'worried'}, {t: 17.8, emotion: 'shock'}, {t: 20.82, emotion: 'worried'}, {t: 23.03, emotion: 'flat'}, {t: 25.61, emotion: 'squint'}, {t: 27.65, emotion: 'flat'}, {t: 32.82, emotion: 'worried'}, {t: 35.65, emotion: 'squint'}, {t: 39.95, emotion: 'worried'}, {t: 43.73, emotion: 'flat'}, {t: 48.86, emotion: 'worried'}],
  RAY: [{t: 0, emotion: 'squint'}, {t: 1.98, emotion: 'angry'}, {t: 3.91, emotion: 'shock'}, {t: 8.56, emotion: 'angry'}, {t: 10.25, emotion: 'shock'}, {t: 15.46, emotion: 'smug'}, {t: 17.8, emotion: 'angry'}, {t: 23.03, emotion: 'flat'}, {t: 25.61, emotion: 'worried'}, {t: 27.65, emotion: 'shock'}, {t: 32.82, emotion: 'flat'}, {t: 35.65, emotion: 'squint'}, {t: 39.95, emotion: 'angry'}, {t: 43.73, emotion: 'worried'}, {t: 48.86, emotion: 'flat'}],
};

/** The expression in force for `who` at a global frame. */
export const emotionAt = (who: string, f: number): string => {
  const beats = FACES[who];
  if (!beats || !beats.length) return 'neutral';
  const t = f / 30;
  let cur = beats[0].emotion;
  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }
  return cur;
};
