/**
 * case0003_faces.ts — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case 3
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {t: number; emotion: string};

export const FACES: Record<string, FaceBeat[]> = {
  DEE: [{t: 0, emotion: 'neutral'}, {t: 0.6, emotion: 'flat'}, {t: 6.46, emotion: 'squint'}, {t: 13.92, emotion: 'flat'}, {t: 16.04, emotion: 'squint'}, {t: 17.77, emotion: 'flat'}, {t: 22.15, emotion: 'worried'}, {t: 24.29, emotion: 'flat'}, {t: 27.39, emotion: 'squint'}, {t: 33.1, emotion: 'shock'}, {t: 34.54, emotion: 'flat'}, {t: 38.88, emotion: 'angry'}, {t: 42.19, emotion: 'flat'}, {t: 46.31, emotion: 'worried'}, {t: 50.09, emotion: 'flat'}],
  RAY: [{t: 0, emotion: 'neutral'}, {t: 0.6, emotion: 'squint'}, {t: 2.56, emotion: 'angry'}, {t: 3.63, emotion: 'squint'}, {t: 6.46, emotion: 'smug'}, {t: 13.92, emotion: 'angry'}, {t: 16.04, emotion: 'flat'}, {t: 17.77, emotion: 'angry'}, {t: 22.15, emotion: 'flat'}, {t: 24.29, emotion: 'angry'}, {t: 27.39, emotion: 'squint'}, {t: 31.77, emotion: 'flat'}, {t: 33.1, emotion: 'squint'}, {t: 34.54, emotion: 'angry'}, {t: 38.88, emotion: 'flat'}, {t: 42.19, emotion: 'squint'}, {t: 46.31, emotion: 'angry'}, {t: 50.09, emotion: 'flat'}],
};

/** The expression in force for `who` at a global frame. */
export const emotionAt = (who: string, f: number): string => {
  const beats = FACES[who];
  if (!beats || !beats.length) return 'neutral';
  const t = f / 30;
  let cur = beats[0].emotion;
  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }
  return cur;
};
