/**
 * case0003_captions.ts — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case 3
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the 1.5s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {start: number; end: number; who: string; text: string};

export const CAPTIONS: Cue[] = [
  {start: 0.6, end: 2.248, who: 'DEE', text: 'One eviction case.'},
  {start: 2.6, end: 3.044, who: 'RAY', text: 'Okay.'},
  {start: 4.6, end: 6.631, who: 'DEE', text: 'That report goes to a landlord.'},
  {start: 7.4, end: 11.27, who: 'RAY', text: 'Evicted. Evicted. Yeah, no. Career defendant.'},
  {start: 11.6, end: 12.884, who: 'RAY', text: 'He got sued once.'},
  {start: 14.0, end: 15.153, who: 'DEE', text: 'I asked where they got it.'},
  {start: 16.2, end: 17.716, who: 'RAY', text: 'Somebody got paid to do that.'},
  {start: 23.8, end: 25.23, who: 'RAY', text: 'I\'ve been standing here the whole time.'},
  {start: 26.6, end: 27.128, who: 'DEE', text: 'I know.'},
  {start: 32.6, end: 35.862, who: 'INSTITUTION', text: 'reasonable procedures to ensure maximum possible accuracy'},
  {start: 36.1, end: 37.025, who: 'DEE', text: 'He disputed it.'},
  {start: 37.9, end: 38.67, who: 'INSTITUTION', text: 'Invalid.'},
  {start: 39.5, end: 42.739, who: 'RAY', text: 'That\'s not a decision. That\'s a fucking word.'},
  {start: 43.1, end: 45.06, who: 'DEE', text: 'Sorry, is there a second word?'},
  {start: 46.3, end: 49.368, who: 'DEE', text: 'The landlord\'s copy and his copy don\'t say the same thing.'},
  {start: 50.3, end: 52.427, who: 'RAY', text: 'So. Which one of those do I live in?'},
  {start: 54.1, end: 56.747, who: 'RAY', text: 'Mine\'s still under there.'},
];

/** Seconds of finished episode: last spoken word plus the 1.5s tail. */
export const TOTAL = 58.25;

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
};
