/**
 * case0003_captions.ts — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case 3
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the 1.5s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {start: number; end: number; who: string; text: string};

export const CAPTIONS: Cue[] = [
  {start: 0.0, end: 4.117, who: 'RAY', text: 'There is a company that decides if you are allowed to rent.'},
  {start: 4.38, end: 6.999, who: 'DEE', text: 'RentGrow. The government sued them in July.'},
  {start: 7.26, end: 8.012, who: 'RAY', text: 'For what?'},
  {start: 8.27, end: 12.284, who: 'DEE', text: 'Their reports said people were evicted more times than they were.'},
  {start: 12.54, end: 13.946, who: 'RAY', text: 'How do you get that wrong?'},
  {start: 14.21, end: 17.311, who: 'DEE', text: 'They counted the same eviction twice.'},
  {start: 17.57, end: 19.337, who: 'RAY', text: 'The same eviction.'},
  {start: 19.6, end: 22.521, who: 'DEE', text: 'It is one case, listed twice.'},
  {start: 22.78, end: 26.168, who: 'RAY', text: 'So you call and say, it is one eviction.'},
  {start: 26.43, end: 28.438, who: 'DEE', text: 'They marked the dispute invalid.'},
  {start: 28.69, end: 29.299, who: 'RAY', text: 'And?'},
  {start: 29.56, end: 34.166, who: 'DEE', text: 'When people asked what was in their file, they left out where it came from.'},
  {start: 34.43, end: 36.931, who: 'RAY', text: 'So you cannot even find the thing to argue with.'},
  {start: 37.19, end: 40.492, who: 'DEE', text: 'And told the landlord something different than they told you.'},
  {start: 40.75, end: 43.208, who: 'RAY', text: 'I am not the customer.'},
  {start: 43.47, end: 43.873, who: 'DEE', text: 'No.'},
  {start: 44.13, end: 48.654, who: 'INSTITUTION', text: 'Reasonable procedures to assure maximum possible accuracy.'},
  {start: 48.92, end: 51.151, who: 'RAY', text: 'They paid two and a quarter million dollars.'},
  {start: 51.41, end: 54.245, who: 'RAY', text: 'The landlord is still their customer tomorrow.'},
];

/** Seconds of finished episode: last spoken word plus the 1.5s tail. */
export const TOTAL = 55.74;

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
};
