/**
 * case0004_captions.ts — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case 4
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the 1.5s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {start: number; end: number; who: string; text: string};

export const CAPTIONS: Cue[] = [
  {start: 0.0, end: 1.633, who: 'DEE', text: 'They denied the nursing home.'},
  {start: 1.98, end: 3.404, who: 'RAY', text: 'He just left the hospital.'},
  {start: 3.91, end: 7.864, who: 'DEE', text: 'You appeal, they say yes. Ninety-five percent.'},
  {start: 8.56, end: 9.744, who: 'RAY', text: 'So they were wrong.'},
  {start: 10.25, end: 14.569, who: 'DEE', text: 'UnitedHealth\'s own number: ninety-nine point seven.'},
  {start: 15.46, end: 17.0, who: 'RAY', text: 'That\'s a hundred percent with a typo.'},
  {start: 17.8, end: 20.312, who: 'RAY', text: 'So it was never a no. It was a question.'},
  {start: 20.82, end: 22.029, who: 'RAY', text: 'Are you gonna argue.'},
  {start: 23.03, end: 24.913, who: 'DEE', text: 'Eighteen percent argue.'},
  {start: 25.61, end: 26.751, who: 'RAY', text: 'The other eighty-two?'},
  {start: 27.65, end: 31.725, who: 'DEE', text: 'Paid out of pocket. Or gone without post-acute care.'},
  {start: 32.82, end: 34.747, who: 'RAY', text: 'It\'s on the list like an option.'},
  {start: 35.65, end: 38.748, who: 'INSTITUTION', text: 'Your appeal rights are in your plan materials.'},
  {start: 39.95, end: 43.059, who: 'RAY', text: 'Wrong every fucking time somebody checked.'},
  {start: 43.96, end: 47.794, who: 'DEE', text: 'Same finding in 2018. Seventy-five percent.'},
  {start: 49.09, end: 50.157, who: 'RAY', text: 'It\'s going up.'},
];

/** Seconds of finished episode: last spoken word plus the 1.5s tail. */
export const TOTAL = 51.66;

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
};
