/**
 * case0003_faces.ts — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case 3
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {t: number; emotion: string};

export const FACES: Record<string, FaceBeat[]> = {
  DEE: [{t: 0, emotion: 'squint'}, {t: 3.62, emotion: 'flat'}, {t: 8.92, emotion: 'smug'}, {t: 10.04, emotion: 'flat'}, {t: 16.55, emotion: 'squint'}, {t: 19.58, emotion: 'flat'}, {t: 24.94, emotion: 'squint'}, {t: 28.04, emotion: 'flat'}, {t: 30.22, emotion: 'squint'}, {t: 37.02, emotion: 'smug'}],
  RAY: [{t: 0, emotion: 'flat'}, {t: 3.62, emotion: 'squint'}, {t: 6.95, emotion: 'angry'}, {t: 8.92, emotion: 'squint'}, {t: 10.04, emotion: 'angry'}, {t: 13.84, emotion: 'shock'}, {t: 16.55, emotion: 'smug'}, {t: 19.58, emotion: 'shock'}, {t: 22.87, emotion: 'angry'}, {t: 24.94, emotion: 'shock'}, {t: 28.04, emotion: 'squint'}, {t: 30.22, emotion: 'flat'}, {t: 37.02, emotion: 'smug'}],
};

/** The expression in force for `who` at a global frame. */
export const emotionAt = (who: string, f: number): string => {
  const beats = FACES[who];
  if (!beats || !beats.length) return 'neutral';
  const t = f / 30;
  let cur = beats[0].emotion;
  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }
  return cur;
};
