#!/usr/bin/env python3
"""gen_faces_ts.py — compile per-line FACE direction into a timeline track.

WHY THIS EXISTS
Case 0002 had THREE expression changes in fifty-two seconds. Dee held one face
for roughly thirty-six straight seconds, because two of the seven shots never set
her emotion at all and the cast default quietly took over. The owner's verdict
was that faces don't move and it was impossible to feel anything, and they were
right: emotion was a per-SHOT constant, so a nine second shot was a nine second
face.

The mouth comes from the audio, because loudness is a measurable fact. An
EXPRESSION is not measurable, it is a writing decision, so it belongs in the
script next to the claim-ids, authored by whoever wrote the line.

THE LISTENER IS THE POINT
A `face` entry may name any character, not just the speaker. That is deliberate
and it is the whole reason this file exists: in a two-hander the joke lands on
the face of the person who is NOT talking. A script that only ever directs the
speaker has not used this.

  script.json line:
    {"t": 9.87, "who": "DEE", "text": "...", "claims": ["c9"],
     "face": {"DEE": "flat", "RAY": "squint"}}

An entry sets that character's expression FROM that line until something changes
it. Registers are Character.tsx's Emotion union.

  python3 scripts/gen_faces_ts.py --case 2
  python3 scripts/gen_faces_ts.py --case 2 --check
  python3 scripts/gen_faces_ts.py --self-test

Exit 0 pass, 1 fail.
"""
import argparse
import json
import os
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(REPO, "out", "dispatch")
SRC = os.path.join(REPO, "video-engine", "src")
FPS = 30

# Must match Character.tsx's Emotion union. A typo here is silent: an unknown
# string falls through every `emotion === ...` test and renders a browless,
# mouthless face, which is worse than the wrong expression.
EMOTIONS = {"neutral", "angry", "worried", "shock", "smug", "flat", "squint"}

# Who can hold a face. The Institution is a rectangle and never gets one.
CHARACTERS = ("RAY", "DEE")

HEADER = '''/**
 * {name} — GENERATED by scripts/gen_faces_ts.py from the script's `face` direction.
 *
 * DO NOT HAND-EDIT. Regenerate:  python3 scripts/gen_faces_ts.py --case {case}
 *
 * Per-character expression over the episode timeline. An entry holds until the
 * next one, so `emotionAt` is a lookup and never a guess.
 *
 * Case 0002 had THREE expression changes in 52 seconds because emotion was a
 * per-shot constant, which is why nothing on screen read as feeling anything.
 * Faces are authored per LINE now, for the listener as well as the speaker,
 * because in a two-hander the joke lands on the face of whoever is not talking.
 */
export type FaceBeat = {{t: number; emotion: string}};
'''


def build(lines, characters=CHARACTERS):
    """-> {who: [(t, emotion), ...]} sorted, with a starting beat at t=0."""
    tracks = {c: [] for c in characters}
    for ln in sorted(lines, key=lambda l: float(l.get("t", 0))):
        face = ln.get("face") or {}
        for who, emo in face.items():
            who = who.upper()
            if who not in tracks:
                continue
            tracks[who].append((round(float(ln["t"]), 3), emo))
    for who, beats in tracks.items():
        if not beats or beats[0][0] > 0:
            beats.insert(0, (0.0, "neutral"))
        # collapse a beat that repeats the expression already in force: it is not
        # a change, and counting it as one would let a script pass the face gate
        # by restating the same face on every line.
        out, prev = [], None
        for t, e in beats:
            if e != prev:
                out.append((t, e))
                prev = e
        tracks[who] = out
    return tracks


def validate(lines, characters=CHARACTERS):
    """-> list of problems. An unknown register is silent in the rig, so it is
    caught HERE rather than discovered as a blank face in a render."""
    bad = []
    for ln in lines:
        for who, emo in (ln.get("face") or {}).items():
            if who.upper() not in characters:
                bad.append(f"t={ln.get('t')}: face names '{who}', not one of {list(characters)}")
            if emo not in EMOTIONS:
                bad.append(f"t={ln.get('t')}: '{emo}' is not a register "
                           f"({', '.join(sorted(EMOTIONS))})")
    return bad


def render_ts(tracks, case, name):
    body = []
    for who in sorted(tracks):
        rows = ", ".join("{t: %g, emotion: '%s'}" % (t, e) for t, e in tracks[who])
        body.append(f"  {who}: [{rows}],")
    return (HEADER.format(name=name, case=case)
            + "\nexport const FACES: Record<string, FaceBeat[]> = {\n"
            + "\n".join(body) + "\n};\n\n"
            + "/** The expression in force for `who` at a global frame. */\n"
            + "export const emotionAt = (who: string, f: number): string => {\n"
            + f"  const beats = FACES[who];\n"
            + f"  if (!beats || !beats.length) return 'neutral';\n"
            + f"  const t = f / {FPS};\n"
            + "  let cur = beats[0].emotion;\n"
            + "  for (const b of beats) { if (t >= b.t) cur = b.emotion; else break; }\n"
            + "  return cur;\n};\n")


def self_test():
    ok = True
    lines = [
        {"t": 0.0, "who": "RAY", "face": {"RAY": "angry", "DEE": "flat"}},
        {"t": 4.0, "who": "DEE", "face": {"DEE": "smug"}},
        {"t": 8.0, "who": "RAY", "face": {"RAY": "shock"}},
    ]
    tr = build(lines)
    checks = [
        ("tracks both characters", set(tr) == {"RAY", "DEE"}),
        ("an entry holds until the next", tr["RAY"] == [(0.0, "angry"), (8.0, "shock")]),
        ("the LISTENER can be directed too", tr["DEE"][0][1] == "flat"),
        ("starts every character at t=0", all(b[0][0] == 0.0 for b in tr.values())),
    ]

    # A repeated expression is NOT a change. Without this a script could restate
    # the same face on every line and sail through the face gate.
    same = build([{"t": 0.0, "face": {"RAY": "angry"}},
                  {"t": 3.0, "face": {"RAY": "angry"}},
                  {"t": 6.0, "face": {"RAY": "angry"}}])
    checks.append(("a restated expression is not counted as a change",
                   len(same["RAY"]) == 1))

    # RED: an unknown register renders a blank face in the rig and nothing errors.
    checks.append(("catches a register the rig cannot draw",
                   bool(validate([{"t": 0, "face": {"RAY": "furious"}}]))))
    checks.append(("catches a face aimed at a character who has none",
                   bool(validate([{"t": 0, "face": {"INSTITUTION": "angry"}}]))))
    checks.append(("accepts a valid direction",
                   not validate([{"t": 0, "face": {"RAY": "squint"}}])))

    ts = render_ts(tr, 9, "case0009_faces.ts")
    checks.append(("emits emotionAt", "export const emotionAt" in ts))
    checks.append(("says it is generated and how to regenerate", "--case 9" in ts))

    for name, good in checks:
        print(f"  {'ok  ' if good else 'FAIL'} {name}")
        ok &= bool(good)
    print("\nself-test: " + ("both directions correct, as designed" if ok else "THE GATE IS WRONG"))
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", type=int)
    ap.add_argument("--script", default=os.path.join(OUT, "script.json"))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if a.case is None:
        print("gen_faces_ts: --case is required", file=sys.stderr)
        return 2

    name = f"case{a.case:04d}_faces.ts"
    dest = os.path.join(SRC, name)
    try:
        lines = json.load(open(a.script))["lines"]
    except Exception as e:
        print(f"gen_faces_ts: cannot read {a.script}: {e}", file=sys.stderr)
        return 1

    bad = validate(lines)
    if bad:
        print("gen_faces_ts: FAIL, the script directs faces the rig cannot draw:",
              file=sys.stderr)
        for b in bad:
            print("  " + b, file=sys.stderr)
        return 1

    text = render_ts(build(lines), a.case, name)
    if a.check:
        cur = open(dest).read() if os.path.exists(dest) else ""
        if cur == text:
            print(f"gen_faces_ts: {name} is current")
            return 0
        print(f"gen_faces_ts: FAIL {name} is STALE. Run: python3 scripts/gen_faces_ts.py "
              f"--case {a.case}", file=sys.stderr)
        return 1

    open(dest, "w").write(text)
    tr = build(lines)
    print(f"gen_faces_ts: wrote {dest}")
    for who in sorted(tr):
        print(f"  {who:<4} {len(tr[who])} expression(s): "
              + " -> ".join(f"{e}@{t:g}s" for t, e in tr[who]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
