#!/usr/bin/env python3
"""gen_captions_ts.py — write video-engine/src/caseNNNN_captions.ts from the VO.

WHY THIS IS A TOOL AND NOT A PASTE
Case 0002's cue file was generated by hand twice on 2026-08-02, once per
re-synthesis, and each pass meant retyping twelve start/end pairs and a TOTAL
into two different files. That is a transcription job done by a model at 2am,
which is exactly the kind of work that silently drifts: a cue end that no longer
matches the take, a speaker label that survives a recast, a durationInFrames
that still describes the previous cut. The picture then disagrees with the audio
and no gate can see it, because both files are internally consistent.

So the cue file is DERIVED, every time, from out/dispatch/vo_lines.json, which
is itself written from the takes that were actually synthesized.

  python3 scripts/gen_captions_ts.py --case 2
  python3 scripts/gen_captions_ts.py --case 2 --check     # CI: is it stale?
  python3 scripts/gen_captions_ts.py --self-test

--check is the gate half. It regenerates in memory and diffs, so a run that
edits the script and forgets to regenerate fails loudly instead of rendering
last cut's captions over this cut's audio.

Exit 0 pass, 1 fail.
"""
import argparse
import json
import os
import re
import sys

# scripts/ on the path, so `captions_text` resolves however this file is
# invoked. It is imported for strip_tags: ONE definition of what a viewer
# is allowed to read.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(REPO, "out", "dispatch")
SRC = os.path.join(REPO, "video-engine", "src")
TAIL = 1.5

HEADER = '''/**
 * {name} — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case {case}
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the {tail}s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {{start: number; end: number; who: string; text: string}};
'''

FOOTER = '''
/** Seconds of finished episode: last spoken word plus the {tail}s tail. */
export const TOTAL = {total};

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {{
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
}};
'''


from captions_text import strip_tags   # ONE definition; see that module


def ts_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render(lines, case, name, tail=TAIL):
    total = round(max(l["end"] for l in lines) + tail, 2)
    body = ["export const CAPTIONS: Cue[] = ["]
    for l in lines:
        body.append("  {start: %s, end: %s, who: %s, text: %s}," % (
            round(l["start"], 3), round(l["end"], 3),
            ts_str(l["who"]), ts_str(strip_tags(l["text"]))))
    body.append("];")
    return (HEADER.format(name=name, case=case, tail=tail)
            + "\n" + "\n".join(body) + "\n"
            + FOOTER.format(tail=tail, total=total))


def is_current(committed, generated):
    """Is the file on disk what the takes would produce?

    Extracted so the self-test can EXERCISE it. The staleness fixture used to
    assert only `out.replace("end: 2.0", ...) != out`, which tests that
    str.replace works, not that --check notices. A case named "catches a cue
    file that no longer matches the takes" that never runs the comparison is
    the same "gate that cannot fail" trap one level down.
    """
    return committed == generated


def self_test():
    ok = True
    lines = [
        {"start": 0.0, "end": 2.0, "who": "RAY", "text": "[flat] It's a test."},
        {"start": 2.5, "end": 4.25, "who": "DEE", "text": "Two."},
    ]
    out = render(lines, 9, "case0009_captions.ts")

    checks = [
        ("strips performance markup from the screen",
         "[flat]" not in out and "It&apos;s a test." not in out and "It\\'s a test." in out),
        ("escapes an apostrophe for a TS single-quoted string", "\\'" in out),
        # "who: '" and not "who: ", because the Cue type declares `who: string`
        # and counting that too made this pass for the wrong reason.
        ("carries the speaker on every cue", out.count("who: '") == 2),
        ("derives TOTAL as last end plus the tail", "export const TOTAL = 5.75;" in out),
        ("exports speakerAt", "export const speakerAt" in out),
        ("says it is generated and how to regenerate", "--case 9" in out),
    ]
    for name, good in checks:
        print(f"  {'ok  ' if good else 'FAIL'} {name}")
        ok &= good

    # RED on purpose, and through the REAL comparison this time: a take whose
    # measured end moved, a caption whose text was edited by hand, and a file
    # that is simply not there.
    red = [
        ("a cue file whose timings no longer match the takes",
         out.replace("end: 2.0", "end: 9.9")),
        ("a caption edited by hand after generation",
         out.replace("Two.", "Three.")),
        ("no committed cue file at all", ""),
    ]
    for name, committed in red:
        good = not is_current(committed, out)
        print(f"  {'ok  ' if good else 'FAIL'} catches: {name}")
        ok &= good
    same = is_current(out, out)
    print(f"  {'ok  ' if same else 'FAIL'} accepts: a cue file that IS current")
    ok &= same

    print("\nself-test: " + ("both directions correct, as designed" if ok else "THE GATE IS WRONG"))
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", type=int, help="episode number, e.g. 2 for Case0002")
    ap.add_argument("--vo-lines", default=os.path.join(OUT, "vo_lines.json"))
    ap.add_argument("--script", default=os.path.join(OUT, "script.json"))
    ap.add_argument("--from-script", action="store_true",
                    help="DRAFT cues from the frozen script times, for staging "
                         "before the VO exists. Never for a ship render.")
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what would be generated")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if a.case is None:
        print("gen_captions_ts: --case is required", file=sys.stderr)
        return 2

    name = f"case{a.case:04d}_captions.ts"
    dest = os.path.join(SRC, name)

    if a.from_script:
        # DRAFT CUES FROM THE FROZEN SCRIPT TIMES, so staging can be rendered and
        # LOOKED AT before a cent of TTS is spent.
        #
        # This is the standing lesson about ordering: iterate the picture against
        # the free checks and synthesize audio ONCE, at the end. Six re-synthesis
        # passes in one session is what exhausted the daily quota, and the run
        # that did it had no way to see the board until it had paid for the VO.
        #
        # These cues are NOT ship quality and are not meant to be. A line's real
        # end comes from its measured take; here it is the next line's start,
        # which is the same assumption the storyboard is cut to. Once vo.wav
        # exists, regenerate WITHOUT this flag: `--check` compares against the
        # real takes and will call this file stale, which is correct.
        try:
            script = json.load(open(a.script))
        except Exception as e:
            print(f"gen_captions_ts: cannot read {a.script}: {e}", file=sys.stderr)
            return 1
        sl = sorted(script["lines"], key=lambda l: l["t"])
        est = float(script.get("estimated_seconds") or 0.0)
        lines = []
        for i, l in enumerate(sl):
            nxt = sl[i + 1]["t"] if i + 1 < len(sl) else est
            lines.append({"idx": i, "who": l["who"], "start": float(l["t"]),
                          "end": round(float(nxt) - 0.12, 3), "text": l["text"]})
        print(f"gen_captions_ts: DRAFT cues from {os.path.relpath(a.script, REPO)} "
              f"(frozen script times, NOT measured takes)")
    else:
        try:
            lines = json.load(open(a.vo_lines))["lines"]
        except Exception as e:
            print(f"gen_captions_ts: cannot read {a.vo_lines}: {e}", file=sys.stderr)
            return 1
    if not lines:
        print("gen_captions_ts: no lines in the VO", file=sys.stderr)
        return 1

    text = render(lines, a.case, name)
    if a.check:
        cur = open(dest).read() if os.path.exists(dest) else ""
        if is_current(cur, text):
            print(f"gen_captions_ts: {name} is current ({len(lines)} cues)")
            return 0
        print(f"gen_captions_ts: FAIL {name} is STALE. The committed cue file is not "
              f"what the synthesized takes produce. Run: python3 scripts/gen_captions_ts.py "
              f"--case {a.case}", file=sys.stderr)
        return 1

    open(dest, "w").write(text)
    total = round(max(l["end"] for l in lines) + TAIL, 2)
    print(f"gen_captions_ts: wrote {dest}")
    print(f"  {len(lines)} cues, spoken ends {max(l['end'] for l in lines):.2f}s, "
          f"TOTAL {total}s -> durationInFrames={int(round(total * 30))} at 30fps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
