#!/usr/bin/env python3
"""gen_captions_ts.py — write video-engine/src/caseNNNN_captions.ts from the VO.

WHY THIS IS A TOOL AND NOT A PASTE
Case 0002's cue file was generated by hand twice on 2026-08-02, once per
re-synthesis, and each pass meant retyping twelve start/end pairs and a TOTAL
into two different files. That is a transcription job done by a model at 2am,
which is exactly the kind of work that silently drifts: a cue end that no longer
matches the take, a speaker label that survives a recast, a durationInFrames
that still describes the previous cut. The picture then disagrees with the audio
and no gate can see it, because both files are internally consistent.

So the cue file is DERIVED, every time, from out/dispatch/vo_lines.json, which
is itself written from the takes that were actually synthesized.

  python3 scripts/gen_captions_ts.py --case 2
  python3 scripts/gen_captions_ts.py --case 2 --check     # CI: is it stale?
  python3 scripts/gen_captions_ts.py --self-test

--check is the gate half. It regenerates in memory and diffs, so a run that
edits the script and forgets to regenerate fails loudly instead of rendering
last cut's captions over this cut's audio.

Exit 0 pass, 1 fail.
"""
import argparse
import json
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(REPO, "out", "dispatch")
SRC = os.path.join(REPO, "video-engine", "src")
TAIL = 1.5

HEADER = '''/**
 * {name} — GENERATED by scripts/gen_captions_ts.py from out/dispatch/vo_lines.json.
 *
 * DO NOT HAND-EDIT. Regenerate instead:  python3 scripts/gen_captions_ts.py --case {case}
 *
 * Each cue's start is the frozen script time the storyboard is also cut to, and
 * each end is the MEASURED duration of the take that was actually synthesized,
 * so the burned-in caption cannot drift from the spoken word.
 *
 * `who` carries the SPEAKER, which does two jobs: it colours and labels the
 * caption, and it drives which character is talking. The engine forbids real
 * lip-sync on purpose (see lib/voice.tsx: figures chat IN the scene, they do not
 * mouth the voiceover), so `who` is a binary is-this-one-talking signal and
 * ambientMouth supplies the generic conversational cycle. Nothing here needs to
 * stay in sync per word.
 *
 * TOTAL is the spoken end plus the {tail}s tail, and it is the ONE number the
 * composition's durationInFrames is derived from.
 */
export type Cue = {{start: number; end: number; who: string; text: string}};
'''

FOOTER = '''
/** Seconds of finished episode: last spoken word plus the {tail}s tail. */
export const TOTAL = {total};

/** Who is speaking at time t, or null in a gap. One definition, so the caption
 *  tint, the speaker label and the talk pose can never disagree. */
export const speakerAt = (t: number): string | null => {{
  const c = CAPTIONS.find((x) => t >= x.start && t <= x.end);
  return c ? c.who : null;
}};
'''


def strip_tags(t):
    """Performance markup is direction for the voice model, never dialogue. It
    must not reach the screen; the same strip lives in vo_cast.cues()."""
    return re.sub(r"\s*\[[^\]]{1,20}\]\s*", " ", t).strip()


def ts_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render(lines, case, name, tail=TAIL):
    total = round(max(l["end"] for l in lines) + tail, 2)
    body = ["export const CAPTIONS: Cue[] = ["]
    for l in lines:
        body.append("  {start: %s, end: %s, who: %s, text: %s}," % (
            round(l["start"], 3), round(l["end"], 3),
            ts_str(l["who"]), ts_str(strip_tags(l["text"]))))
    body.append("];")
    return (HEADER.format(name=name, case=case, tail=tail)
            + "\n" + "\n".join(body) + "\n"
            + FOOTER.format(tail=tail, total=total))


def self_test():
    ok = True
    lines = [
        {"start": 0.0, "end": 2.0, "who": "RAY", "text": "[flat] It's a test."},
        {"start": 2.5, "end": 4.25, "who": "DEE", "text": "Two."},
    ]
    out = render(lines, 9, "case0009_captions.ts")

    checks = [
        ("strips performance markup from the screen",
         "[flat]" not in out and "It&apos;s a test." not in out and "It\\'s a test." in out),
        ("escapes an apostrophe for a TS single-quoted string", "\\'" in out),
        # "who: '" and not "who: ", because the Cue type declares `who: string`
        # and counting that too made this pass for the wrong reason.
        ("carries the speaker on every cue", out.count("who: '") == 2),
        ("derives TOTAL as last end plus the tail", "export const TOTAL = 5.75;" in out),
        ("exports speakerAt", "export const speakerAt" in out),
        ("says it is generated and how to regenerate", "--case 9" in out),
    ]
    for name, good in checks:
        print(f"  {'ok  ' if good else 'FAIL'} {name}")
        ok &= good

    # RED on purpose: a stale file must not pass --check.
    stale = out.replace("end: 2.0", "end: 9.9")
    print(f"  {'ok  ' if stale != out else 'FAIL'} catches: a cue file that no longer matches the takes")
    ok &= stale != out

    print("\nself-test: " + ("both directions correct, as designed" if ok else "THE GATE IS WRONG"))
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", type=int, help="episode number, e.g. 2 for Case0002")
    ap.add_argument("--vo-lines", default=os.path.join(OUT, "vo_lines.json"))
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what would be generated")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if a.case is None:
        print("gen_captions_ts: --case is required", file=sys.stderr)
        return 2

    name = f"case{a.case:04d}_captions.ts"
    dest = os.path.join(SRC, name)
    try:
        lines = json.load(open(a.vo_lines))["lines"]
    except Exception as e:
        print(f"gen_captions_ts: cannot read {a.vo_lines}: {e}", file=sys.stderr)
        return 1
    if not lines:
        print("gen_captions_ts: no lines in the VO", file=sys.stderr)
        return 1

    text = render(lines, a.case, name)
    if a.check:
        cur = open(dest).read() if os.path.exists(dest) else ""
        if cur == text:
            print(f"gen_captions_ts: {name} is current ({len(lines)} cues)")
            return 0
        print(f"gen_captions_ts: FAIL {name} is STALE. The committed cue file is not "
              f"what the synthesized takes produce. Run: python3 scripts/gen_captions_ts.py "
              f"--case {a.case}", file=sys.stderr)
        return 1

    open(dest, "w").write(text)
    total = round(max(l["end"] for l in lines) + TAIL, 2)
    print(f"gen_captions_ts: wrote {dest}")
    print(f"  {len(lines)} cues, spoken ends {max(l['end'] for l in lines):.2f}s, "
          f"TOTAL {total}s -> durationInFrames={int(round(total * 30))} at 30fps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
